### ISSUE TITLE
Question about Appodeal Android SDK v3.1.3

### ISSUE THREAD

**Issue by 201949** [DmitriiFeshchenko/godot-appodeal-android-plugin#1]
Hello Dmitrii,

Are you planning to update the Godot 3.5.x plugin to Appodeal Android SDK version 3.1.3?

**Comment by dmitriifeshchenko** [comment]
Hello, @201949.

Yes, I do plan to update this plugin to v3.1.3 and also to the latest v3.2.0-beta. Unfortunately, it's a low priority now, so I can't let you know the exact ETA at the moment. Probably the updated plugin will be published in November.

**Comment by 201949** [comment]
Hello Dmitrii,

Appodeal SDK 3.2.0 has been released and version 3.1.3 is outdated. I tried to successfully rebuild your plugin for version 3.1.3.+, but unfortunately it doesn’t work for version 3.2.0. Are you still planning a new version for Godot?

**Comment by dmitriifeshchenko** [comment]
Hi, @201949! I know that v3.2.0 was released, cause I did release it. Yes, I will update the Godot plugin to v3.2.0 as soon as I have a chance. Sorry for the delay, but I am currently under a heavy load. 😭

**Comment by 201949** [comment]
Dmitrii,

Thank you for the clarification. Appodeal offers participation in the project acceleration program, but for this you need SDK 3.2.0. To my regret, I was able to rebuild your plugin only to version 3.1.3 and asked Appodeal technical support about the sufficiency of this version. My problem is that I use Godot 3.5.2 for my projects, and the new SDK is written in Kotlin and compiled by Gradle 8.2. Nevertheless, good luck in solving your difficult tasks!

**Comment by dmitriifeshchenko** [comment]
@201949, v2.0.0 Godot Appodeal plugin was just released. It contains Appodeal SDK v3.2.0 and was built for Godot v3.5.3. I tested both iOS and Android builds, everything works as expected.

**Comment by 201949** [comment]
Thank you! Appodeal SDK 3.2.1-beta is now available in accordance with Google's consent management requirements, which will go into effect on January 16th. Will it be enough to specify the beta repository https://artifactory.appodeal.com/appodeal-beta-public and the dependency com.appodeal.ads:sdk:3.2.1.0-beta.1 in the configuration?

**Comment by dmitriifeshchenko** [comment]
Version 3.2.1-beta.1 has no API changes compared to version 3.2.0 which could break the Godot plugin v2.0.0. So just changing the configuration may work for you. But you only need to update to this version if you use AdMob. Also, be sure to check the [instructions](https://docs.appodeal.com/advanced/google-cmp-and-tcfv2-support) because setting up this CM can be a bit tricky.

**Comment by 201949** [comment]
Thanks for your clarification! I have already built an old version modified plugin with SDK Appodil 3.2.0 with Firebase support enabled and collected statistics. Now I'll try your updated plugin. In turn, I would like to add that in the app level build.gradle file the dependency <compileOnly fileTree(dir:"libs", include:["godot-lib.3.5.3.stable.release.aar"])> can be replaced with a shorter compileOnly "org.godotengine:godot:3.5.3.stable", which will reduce the size of the repository.
